//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapbase_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int PatientID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> subscriptionID { get; set; }
        public int TargetID { get; set; }
        public int ReprotID { get; set; }
        public Nullable<int> AppointmentID { get; set; }
        public Nullable<int> ExerciseID { get; set; }
        public Nullable<int> CaloriesID { get; set; }
        public int WeightID { get; set; }
        public string Title { get; set; }
        public string FristName { get; set; }
        public string SurName { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<int> HomePhone { get; set; }
        public Nullable<int> MobilePhone { get; set; }
        public string Ethnicity { get; set; }
        public string FamilyStructure { get; set; }
        public string EmploymentStatus { get; set; }
        public string Occupation { get; set; }
        public string ChildrenName { get; set; }
        public string ChildrenAge { get; set; }
        public string ChildrenGender { get; set; }
        public Nullable<System.DateTime> CreatedData { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedData { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
